language: csharp
solution: server/dotnet/TinyBI.sln
mono: none
dotnet: 3.1
script:
    - pushd server/dotnet
    - node version-up.mjs $TRAVIS_TAG
    - dotnet build
    - dotnet test TinyBI.Engine.Tests/TinyBI.Engine.Tests.csproj
    - popd
deploy:
  - provider: script
    script: bash release.sh $TRAVIS_TAG
    on:
      branch: master
      tags: true
