language: csharp
solution: server/dotnet/TinyBI.sln
mono: none
dotnet: 3.1
script:
    - pushd server/dotnet
    - node apply-version.js
    - dotnet build
    - dotnet test TinyBI.Engine.Tests/TinyBI.Engine.Tests.csproj
    - popd
deploy:
  - provider: script
    script: bash release.sh
    on:
      branch: master